// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $blog_postname_ from "./routes/blog/[postname].tsx";
import * as $cube from "./routes/cube.tsx";
import * as $index from "./routes/index.tsx";
import * as $partials_blog_postname_ from "./routes/partials/blog/[postname].tsx";
import * as $partials_cube from "./routes/partials/cube.tsx";
import * as $partials_home from "./routes/partials/home.tsx";
import * as $partials_snake from "./routes/partials/snake.tsx";
import * as $snake from "./routes/snake.tsx";
import * as $AnimatedText3D from "./islands/AnimatedText3D.tsx";
import * as $BackButton3D from "./islands/BackButton3D.tsx";
import * as $CopyableCodeBlock from "./islands/CopyableCodeBlock.tsx";
import * as $CopyableText from "./islands/CopyableText.tsx";
import * as $DynamicMarkdownItem from "./islands/DynamicMarkdownItem.tsx";
import * as $ResizeDetector from "./islands/ResizeDetector.tsx";
import * as $SpinningCube from "./islands/SpinningCube.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.tsx": $_middleware,
    "./routes/api/joke.ts": $api_joke,
    "./routes/blog/[postname].tsx": $blog_postname_,
    "./routes/cube.tsx": $cube,
    "./routes/index.tsx": $index,
    "./routes/partials/blog/[postname].tsx": $partials_blog_postname_,
    "./routes/partials/cube.tsx": $partials_cube,
    "./routes/partials/home.tsx": $partials_home,
    "./routes/partials/snake.tsx": $partials_snake,
    "./routes/snake.tsx": $snake,
  },
  islands: {
    "./islands/AnimatedText3D.tsx": $AnimatedText3D,
    "./islands/BackButton3D.tsx": $BackButton3D,
    "./islands/CopyableCodeBlock.tsx": $CopyableCodeBlock,
    "./islands/CopyableText.tsx": $CopyableText,
    "./islands/DynamicMarkdownItem.tsx": $DynamicMarkdownItem,
    "./islands/ResizeDetector.tsx": $ResizeDetector,
    "./islands/SpinningCube.tsx": $SpinningCube,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
